openapi: 3.0.3
info:
  title: TailoredMedia Annotation Store
  description: TailoredMedia Annotation Store
  version: 1.0.0
servers:
  - url: 'https://localhost:4000/resources'
paths:
  /annotations:
    get:
      operationId: listAnnotations
      summary: List all annotations
      tags:
        - Annotation
      responses:
        default:
          $ref: '#/components/responses/AnnotationListResponse'
    post:
      operationId: Create Annotations
      summary: Post one or multiple Annotations
      tags:
        - Annotation
      requestBody:
        $ref: '#/components/requestBodies/AnnotationRequestBody'
      responses:
        default:
          $ref: '#/components/responses/IdResponse'
  /annotations/{annotationId}:
    get:
      operationId: getAnnotation
      summary: Get specific annotation
      tags:
        - Annotation
      parameters:
        - $ref: '#/components/parameters/AnnotationId'
      responses:
        default:
          $ref: '#/components/responses/AnnotationResponse'

tags:
  - name: Annotation
    description: ''
components:
  schemas:
    Id:
      type: string
    DateTime:
      type: string
      format: date-time
      example: "2021-11-29T16:02:17.123Z"
    OriginType:
      description: ''
      type: string
      enum:
        - ingest
        - linking
        - manual
    Origin:
      description: ''
      type: object
      properties:
        type:
          allOf:
            - $ref: '#/components/schemas/OriginType'
        creator:
          type: string
    BodyType:
      description: ''
      type: string
      enum:
        - MetadataBody
        - ResourceBody
        - TextBody
        - PartBody
    Body:
      description: ''
      type: object
      required:
        - id
        - confidence
        - type
      properties:
        id:
          type: string
        confidence:
          type: number
          minimum: 0
          maximum: 100
        type:
          allOf:
            - $ref: '#/components/schemas/BodyType'
    TextBody:
      description: ''
      allOf:
        - $ref: '#/components/schemas/Body'
        - type: object
          required:
            - value
          properties:
            value:
              type: string
    MetadataBody:
      description: ''
      allOf:
        - $ref: '#/components/schemas/Body'
        - type: object
          required:
            - relation
            - value
          properties:
            relation:
              type: string
            value:
              type: array
              items:
                type: object
    ResourceBody:
      description: ''
      allOf:
        - $ref: '#/components/schemas/Body'
        - type: object
          required:
            - relation
            - value
          properties:
            relation:
              type: string
            value:
              type: string
    PartBody:
      description: ''
      allOf:
        - $ref: '#/components/schemas/Body'
        - type: object
    TargetType:
      description: ''
      type: string
      enum:
        - TargetResource
        - FragmentResource
    Target:
      description: ''
      type: object
      required:
        - source
        - type
      properties:
        source:
          type: string
        type:
          allOf:
            - $ref: '#/components/schemas/TargetType'
    TargetResource:
      allOf:
        - $ref: '#/components/schemas/Target'
        - type: object
    FragmentResource:
      allOf:
        - $ref: '#/components/schemas/Target'
        - type: object
          required:
            - selector
          properties:
            selector:
              oneOf:
                - $ref: '#/components/schemas/Selector'
                - $ref: '#/components/schemas/TextPositionSelector'
                - $ref: '#/components/schemas/TextQuoteSelector'
                - $ref: '#/components/schemas/MediaFragmentSelector'
                - $ref: '#/components/schemas/TemporalFragmentSelector'
                - $ref: '#/components/schemas/PercentSpatialSelector'
    SelectorType:
      description: ''
      type: string
      enum:
        - TextPositionSelector
        - TextQuoteSelector
        - MediaFragmentSelector
        - TemporalFragmentSelector
        - PercentSpatialSelector
    Selector:
      description: ''
      type: object
      required:
        - type
      properties:
        type:
          allOf:
            - $ref: '#/components/schemas/SelectorType'
    TextPositionSelector:
      allOf:
        - $ref: '#/components/schemas/Selector'
        - type: object
          required:
            - start
            - end
          properties:
            start:
              type: number
            end:
              type: number
    TextQuoteSelector:
      allOf:
        - $ref: '#/components/schemas/Selector'
        - type: object
          required:
            - exact
            - prefix
            - suffix
          properties:
            exact:
              type: string
            prefix:
              type: string
            suffix:
              type: string
    TemporalFragmentSelector:
      allOf:
        - $ref: '#/components/schemas/Selector'
        - type: object
          required:
            - start
            - end
          properties:
            start:
              type: number
            end:
              type: number
    PercentSpatialSelector:
      allOf:
        - $ref: '#/components/schemas/Selector'
        - type: object
          required:
            - x
            - y
            - w
            - h
          properties:
            x:
              type: number
            y:
              type: number
            w:
              type: number
            h:
              type: number
    MediaFragmentSelector:
      allOf:
        - $ref: '#/components/schemas/Selector'
        - type: object
          required:
            - temporal
            - spatial
          properties:
            temporal:
              allOf:
                - $ref: '#/components/schemas/TemporalFragmentSelector'
              nullable: true
            spatial:
              allOf:
                - $ref: '#/components/schemas/PercentSpatialSelector'
              nullable: true
    Annotation:
      description: ''
      type: object
      properties:
        id:
          type: string
          readOnly: true
        origin:
          allOf:
            - $ref: '#/components/schemas/Origin'
        replaces:
          type: string
          nullable: true
        replacedBy:
          type: string
          nullable: true
        created:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          readOnly: true
        body:
          oneOf:
            - $ref: '#/components/schemas/MetadataBody'
            - $ref: '#/components/schemas/ResourceBody'
            - $ref: '#/components/schemas/PartBody'
            - $ref: '#/components/schemas/TextBody'
        target:
            type: array
            items:
              oneOf:
                - $ref: '#/components/schemas/TargetResource'
                - $ref: '#/components/schemas/FragmentResource'
  parameters:
    AnnotationId:
      name: annotationId
      in: path
      schema:
        $ref: '#/components/schemas/Id'
  requestBodies:
    AnnotationRequestBody:
      description: ''
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/Annotation'
              - type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/Annotation'
  responses:
    AnnotationResponse:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Annotation'
    AnnotationListResponse:
      description: ''
      content:
        application/json:
          schema:
            type: array
            items:
              allOf:
                - $ref: '#/components/schemas/Annotation'
    IdResponse:
      description: 'The ID returned as sole id or as dictionary where the key is the old key and the value is the new key'
      content:
        application/json:
          schema:
            oneOf:
              - type: object
                properties:
                  id:
                    type: string
              - type: object
                additionalProperties:
                  type: string