name: Publish
on:
  push:
    tags:
      - v*
jobs:
  Publish-NPM-Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
  notifyOpenAPIClient:
    runs-on: ubuntu-latest
    needs: Publish-NPM-Package
    env:
      OPEN_API_VERSION: 1.0.0
    steps:
      - run: echo "OPEN_API_VERSION=$(cat ./api/doc/spec.yaml | grep "version:" | sed 's/[[:alpha:]|(|[:space:]|:]//g')" >> $GITHUB_ENV
      - run: echo "${{ env.OPEN_API_VERSION }}"
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: TailoredMediaProject/tm-openapi-client-typescript
          event-type: notify-client-generator
          client-payload: '{"openAPIVersion": "${{ 1.0.0 }}"}'
